
services:
  express-server:
    build: .
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    container_name: express-server
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=EyrieMysqlDb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysqlDb
      - redis

  mysqlDb:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: EyrieMysqlDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
  adminer:
    image: adminer:5
    restart: always
    ports:
      - "8080:8080"
    
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
    driver: local
