# Use the official Node.js image
FROM amd64/node:18-alpine

# Set the working directory inside the container
WORKDIR /dockerapp

# Copy package.json and package-lock.json (or yarn.lock) first to take advantage of Docker layer caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the application with a watch command for live reloading (if you're using `tsc` or a tool like `nodemon`)
CMD ["npm", "run", "dev"]
