name: test code
on:
  workflow_run:
    workflows: ["Lint Code"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: npm run test
